var pg = require('pg');

var instruments = [
{
	name: 'Trombone',
	family: 'Brass',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Bass',
},
{
	name: 'Bass Trombone',
	family: 'Brass',
	pitch: 'Concert Pitch',
	sounds: 'P8 lower',
	transposes: 'P8 higher',
	clef: 'Bass',
},
{
	name: 'Tuba',
	family: 'Brass',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Bass',
},
{
	name: 'French Horn',
	family: 'Brass',
	pitch: 'F natural',
	sounds: 'P5 lower',
	transposes: 'P5 higher',
	clef: 'Treble',
},
{
	name: 'Coronet',
	family: 'Brass',
	pitch: 'B-flat',
	sounds: 'M2 lower',
	transposes: 'M2 higher',
	clef: 'Treble',
},
{
	name: 'Drums',
	family: 'Percussion',
	pitch: '',
	sounds: '',
	transposes: '',
	clef: '',
},
{
	name: 'Cymbals',
	family: 'Percussion',
	pitch: '',
	sounds: '',
	transposes: '',
	clef: '',
},
{
	name: 'Piano',
	family: 'Percussion',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Grand Staff',
},
{
	name: 'Triangle',
	family: 'Percussion',
	pitch: '',
	sounds: '',
	transposes: '',
	clef: '',
},
{
	name: 'Chimes',
	family: 'Percussion',
	pitch: '',
	sounds: '',
	transposes: '',
	clef: '',
},
{
	name: 'Glockenspiel',
	family: 'Percussion',
	pitch: '',
	sounds: '',
	transposes: '',
	clef: '',
},
{
	name: 'Timpani',
	family: 'Percussion',
	pitch: '',
	sounds: '',
	transposes: '',
	clef: '',
},
{
	name: 'Bells',
	family: 'Percussion',
	pitch: '',
	sounds: '',
	transposes: '',
	clef: '',
},
{
	name: 'Xylophone',
	family: 'Percussion',
	pitch: '',
	sounds: '',
	transposes: '',
	clef: '',
},
{
	name: 'Vibraphone',
	family: 'Percussion',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Grand Staff',
},
{
	name: 'Mirimba',
	family: 'Percussion',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Treble',
},
{
	name: 'Harpsichord',
	family: 'Strings',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Grand Staff',
},

{
	name: 'Violin',
	family: 'Strings',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Treble',
},
{
	name: 'Cello',
	family: 'Strings',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Bass',
},
{
	name: 'Viola',
	family: 'Strings',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Alto,Treble',
},
{
	name: 'Harp',
	family: 'Strings',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Grand Staff',
},
{
	name: 'Guitar',
	family: 'Strings',
	pitch: 'n/a',
	sounds: 'P8 Lower',
	transposes: 'P8 higher',
	clef: 'Treble',
},
{
	name: 'Double Bass',
	family: 'Strings',
	pitch: 'n/a',
	sounds: 'P8 lower',
	clef: 'Bass',
},
{
	name: 'Flute',
	family: 'Woodwinds',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Treble',
},
{
	name: 'Piccolo',
	family: 'Woodwinds',
	pitch: 'n/a',
	sounds: 'P8 higher',
	transposes: 'P8 lower',
	clef: 'Treble',
},
{
	name: 'Clarinet',
	family: 'Woodwinds',
	pitch: 'Bb',
	sounds: 'M2 lower',
	transposes: 'M2 higher',
	clef: 'Treble',
},
{
	name: 'Clarinet',
	family: 'Woodwinds',
	pitch: 'A',
	sounds: 'm3 lower',
	transposes: 'm3 higher',
	clef: 'Treble',
},
{
	name: 'Clarinet',
	family: 'Woodwinds',
	pitch: 'Eb',
	sounds: 'M6 lower',
	transposes: 'M6 higher',
	clef: 'Treble',
},
{
	name: 'Bass Clarinet',
	family: 'Woodwinds',
	pitch: 'Bb',
	sounds: 'M9 lower',
	transposes: 'M9 higher',
	clef: 'Bass',
},
{
	name: 'Bassoon',
	family: 'Woodwinds',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Bass',
},
{
	name: 'Contrabassoon',
	family: 'Woodwinds',
	pitch: 'n/a',
	sounds: 'P8 lower',
	transposes: 'P8 higher',
	clef: 'Bass',
},
{
	name: 'Oboe',
	family: 'Woodwinds',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Treble',
},
{
	name: 'Organ',
	family: 'Woodwinds',
	pitch: 'Concert Pitch',
	sounds: 'Concert Pitch',
	transposes: 'none',
	clef: 'Treble',
},
];

var client = new pg.Client({
 database: 'instrument_app',
 user: 'instrument_admin',
 password: 'admin'
});

client.connect(function() {
  instruments.forEach(function(instrument) {
    client.query(`
      insert into instruments (
        name,
        family,
        pitch,
        sounds,
        transposes,
        clef
      ) values (
        '${instrument.name}',
        '${instrument.family}',
        '${instrument.pitch}',
        '${instrument.sounds}',
        '${instrument.transposes}',
        '${instrument.clef}'
      );
    `);
  });
});
